### ISSUE TITLE
Compile on stable Rust 2018

### ISSUE THREAD

**Issue by LukasKalbertodt** [auto-impl-rs/auto_impl#13]
It would be neat to be able to use this on stable (once `use_extern_macros` is stabilized). Currently the following features are activated:

- [x] ~~**`#![feature(in_band_lifetimes)]`**: [tracking issue](https://github.com/rust-lang/rust/issues/44524), expected to be stabilized for Rust 2018. If not, we can easily remove the feature by changing one line of code.~~ **=> probably won't be stabilized, so this has been removed from this crate for now.**
- [x] **`#![feature(proc_macro_span)]`**: used only for one `Span::join()` call. I think it's easy to remove `join()` with something we can use on stable. **=> guarded by `nightly` feature (see #26)**
- [x] **`#![feature(proc_macro_diagnostic)]`**: this is the big part! I don't think the `Diagnostics` API will be stabilized in near future. So in order to compile on stable, we need to replace all nice diagnostics with simple panics. This shouldn't be too hard. **=> guarded by `nightly` feature (see #26)**

~~We still use Cargo's `cargo-features = ["edition"]`~~ (EDIT: it's stabilized on nightly and beta RC1 now) with `edition ="2018"` which entails a couple of features. But all of these should be stabilized for Rust 2018 (EDIT: they are now). 

- [x] Implicit `extern crates` (see https://github.com/rust-lang/rust/issues/53128)
- [x] `#![feature(extern_prelude)]` (see https://github.com/rust-lang/rust/issues/53128) 
- [x] ~~`#![feature(crate_visibility_modifier)]` (see https://github.com/rust-lang/rust/issues/53120) (TODO: this might not make it into Rust 2018, maybe switch to `pub(crate)` for now?)~~ -> replaced by `pub(crate)`
- [x] `#![feature(crate_in_paths)]` (see https://github.com/rust-lang/rust/issues/53130)

**Comment by Mark-Simulacrum** [comment]
> replace all nice diagnostics with simple panics.

I would instead use the `compile_error` macro -- that'll give you slightly nicer error messages and it is already stable.

**Comment by LukasKalbertodt** [comment]
@Mark-Simulacrum Awesome idea! I'll certainly try that!

**Comment by LukasKalbertodt** [comment]
I think we should release a new version before the official Rust 2018 release. So I removed the v0.3 milestone.

**Comment by LukasKalbertodt** [comment]
With #31 this crate compiles on beta RC1. So we're on track for having this compile on stable Rust 2018. I guess we'll keep this issue open until the real Rust 2018 is released and we can be sure that all is fine.

**Comment by LukasKalbertodt** [comment]
Seems to work with Rust 2018 (1.31), so I'm gonna close this :)

Happy Rust2018!
